# Site settings
title: Technical Lead | .Net Software Developer
description:  .Net Software Developer, always searching for the next challenge
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: I am an experienced developer with a solid background in a wide range of .NET development aspects in a business application context. My expertise includes all development stages, from initial analysis through design and execution. I am proficient in a variety of platforms and systems. In addition to my technical skills, I am a great communicator and team player. My ability to communicate well enables me to work effectively with clients to identify objectives and requirements for applications.
user_title: Software Engineer
email: kkiran0820@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: murraco
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
